# Generated by Django 6.0.6 on 2026-06-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=10, verbose_name='Відділ/Зона')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('shelf', models.IntegerField(verbose_name='Полиця')),
                ('position', models.IntegerField(verbose_name='Місце')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Зайнята')),
            ],
            options={
                'verbose_name': 'Комірка',
                'verbose_name_plural': 'Комірки',
                'unique_together': {('zone', 'row', 'shelf', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Штрихкод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('cell', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='warehouse.cell', verbose_name='Комірка зберігання')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
