# Generated by Django 6.0.6 on 2026-06-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ADD', 'Додано'), ('REMOVE', 'Вилучено')], max_length=10, verbose_name='Тип дії')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час події')),
            ],
            options={
                'verbose_name': 'Лог складу',
                'verbose_name_plural': 'Логи складу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=10, verbose_name='Відділ/Зона')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('shelf', models.IntegerField(verbose_name='Полиця')),
                ('position', models.IntegerField(verbose_name='Місце')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Зайнята повністю')),
            ],
            options={
                'verbose_name': 'Комірка',
                'verbose_name_plural': 'Комірки',
                'ordering': ['zone', 'row', 'shelf', 'position'],
                'unique_together': {('zone', 'row', 'shelf', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('barcode', models.CharField(max_length=50, verbose_name='Штрихкод')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість товару')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warehouse.cell', verbose_name='Комірка зберігання')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
