# Generated by Django 6.0.6 on 2026-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ADD', 'Додано'), ('REMOVE', 'Вилучено')], max_length=10, verbose_name='Тип дії')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час події')),
            ],
            options={
                'verbose_name': 'Лог складу',
                'verbose_name_plural': 'Логи складу',
                'ordering': ['-created_at'],
            },
        ),
    ]
